
services:

  # Orion is the context broker
  orion:
    image: telefonicaiot/fiware-orion
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo

  # Databases - Orion uses Mongo-DB
  mongo:
    image: mongo:6.0
    hostname: mongo
    container_name: db-mongo
    ports:
      - "27017:27017" 
    command: --nojournal
    volumes:
      - type: volume
        source: mongo-db
        target: /data
      #- type: bind
      #  source: ./mongodb
      #  target: /data
      #  read_only: false

  # Databases - Excel uses MySQL
  mariadb:
    image: mariadb
    hostname: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_DATABASE: xtrachallenge25
      MARIADB_USER: mysql
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: mysql-db
        target: /var/lib/mysql
      - type: bind
        source: ./mysql
        target: /var/lib/mysql
        read_only: false

  xtraserver:
    image: avr24/xtraserver:v2.0
    hostname: xtraserver
    container_name: xtraserver
    depends_on:
      - orion
      - mariadb
    ports:
      - "80:80"
    restart: unless-stopped
    entrypoint: ["node", "server.js"]
    volumes:
      - type: bind
        source: ./server
        target: /home/app
        read_only: false

  mona-rtmp:
    image: monaserver/monaserver
    container_name: mona-rtmp
    restart: unless-stopped
    ports:
      - "554:554"
      - "1935:1935"
      - "1935:1935/udp"
    volumes:
      - type: bind
        source: ./mona-rtmp
        target: /usr/local/bin/www/
        read_only: false

volumes:
  mongo-db: ~