services:
  mona-rtmp:
    image: monaserver/monaserver
    container_name: mona-rtmp
    restart: unless-stopped
    ports:
      - "554:554"
      - "1935:1935"
      - "1935:1935/udp"
    volumes:
      - type: bind
        source: ./mona-rtmp
        target: /usr/local/bin/
        read_only: false